Repository dvjsharma/Drawn2Shoe, pull requests merged in 2024-07, with the labels that each got.

#108 feat: Added Preloader
  client/package.json
  client/src/components/Preloader/Preloader.css
  client/src/components/Preloader/Preloader.json
  client/src/components/Preloader/Preloader.jsx
  client/src/components/layout.jsx
Labels: enhancement, gssoc, level1, Ready

#137 style: Change underline to bold for text in navbar once selected
  client/src/components/Navbar/navbar.jsx
Labels: Ready

#140 fix: fevicon changed in header issue:#126
  client/index.html
  client/src/assets/android-chrome-192x192.png
  client/src/assets/android-chrome-512x512.png
  client/src/assets/apple-touch-icon.png
  client/src/assets/favicon-16x16.png
  client/src/assets/favicon-32x32.png
  client/src/assets/favicon.ico
Labels: gssoc, level1, Ready

#138 feat: !(Breaking) Implemented Prisma ORM and Initial Database Setup
  README.md
  server/.env
  server/app.js
  server/controllers/cart.js
  server/controllers/products.js
  server/controllers/user.js
  server/middlewares/auth.js
  server/package-lock.json
  server/package.json
  server/prisma/migrations/20240711183708_init/migration.sql
  server/prisma/migrations/migration_lock.toml
  server/prisma/schema.prisma
  server/prisma/seed.js
Labels: gssoc, level3, needs code review, needs test

#141 style: fix button background color when clicked in HomeBanner and Navbar
  client/src/components/Guide/guide.jsx
  client/src/components/Home-banner/HomeBanner.jsx
  client/src/components/Home-retailers/index.jsx
  client/src/components/Navbar/navbar.jsx
Labels: gssoc, level1, Ready

#148 fix: Cart Functionality: Added Quantity Modification and Item Removal issue:#50
  client/src/assets/empty_cart.svg
  client/src/components/Cart-Card/index.jsx
  client/src/pages/Cart/index.jsx
  server/controllers/cart.js
  server/routes/cart.js
Labels: gssoc, level2, Ready

#149 feat: Added Back-To-Top Button
  client/package.json
  client/src/components/BackToTop/BackToTop.jsx
  client/src/components/layout.jsx
Labels: gssoc, level1, Ready
