Repository dvjsharma/Drawn2Shoe, pull requests merged in 2024-05, with the labels that each got.

#55 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, gssoc, level1

#51 fix(ui): fixed overflowing background and padding in Customize Now button
  client/src/components/Guide/guide.jsx
Labels: bug, gssoc, level1, needs code review, needs test

#61 fix(ui): removed the arrows in Pincode number input box
  client/src/pages/Signup/signup.jsx
Labels: bug, gssoc, level1

#56 Favicon_navbarBugs_Hover
  client/index.html
  client/src/assets/logo-final.ico
  client/src/assets/shoelogo.jpg
  client/src/assets/shoessss.ico
  client/src/components/Navbar/navbar.jsx
Labels: bug, enhancement, gssoc, level1, needs code review, needs test

#58 enhanced_readme
  README.md
Labels: documentation, gssoc, level1

#32 feat: auth-redux
  client/package-lock.json
  client/package.json
  client/src/components/Navbar/navbar.jsx
  client/src/main.jsx
  client/src/pages/Login/login.jsx
  client/src/redux/auth-slice.js
  client/src/redux/store.js
  server/controllers/user.js
  server/package-lock.json
  server/server.js
  server/yarn.lock
Labels: enhancement, gssoc, level2, needs code review, needs test
