Repository dvjsharma/Drawn2Shoe, pull requests merged in 2024-06, with the labels that each got.

#78 Added ScrollToTop feature fixes #70
  client/src/App.jsx
  client/src/components/ScrollToTop.jsx
Labels: gssoc, level1, needs code review, needs test

#82 Removed depreciated node modules
  server/controllers/user.js
  server/package-lock.json
  server/package.json
Labels: gssoc, level1, Ready

#83 Fixed more than 8 erros on all the pages
  client/src/components/Cart-Card/index.jsx
  client/src/components/Category-card/index.jsx
  client/src/components/Navbar/navbar.jsx
  client/src/components/Product-card/index.jsx
  client/src/pages/Cart/index.jsx
  client/src/pages/Categories/categories.jsx
  client/src/pages/Customize/customize.jsx
  client/src/pages/Shop/shop.jsx
Labels: bug, gssoc, level1, Ready

#92 feat: add pr title checker workflow
  .github/pr-title-checker.json
  .github/workflows/pr-title-checker.yml
Labels: enhancement, gssoc, level1, Ready

#88 fixed the overall ui
  client/src/components/Carousel2/index.jsx
  client/src/components/Footer/index.jsx
  client/src/components/Guide/guide.jsx
  client/src/components/Home-banner/HomeBanner.jsx
  client/src/components/carousel/index.jsx
  client/src/components/layout.jsx
Labels: level1, title needs formatting

#99 feat: Added Custom Scrollbar
  client/src/App.css
  client/src/App.jsx
Labels: gssoc, level1, needs code review, needs test

#86 feat: Fixed form Handling of products
  client/src/pages/Product/index.jsx
  server/middlewares/auth.js
Labels: work in progress
